modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Rattien/Lux/issues"

[[mods]]
  modId="lux"
  version="${file.jarVersion}"
  displayName="Lux"
  #displayURL=""
  #logoFile="logo.png"
  authors="Rattien"
  description="An illuminating new magic mod for Minecraft"

  [[dependencies.lux]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.lux]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"